version: '3'

services:
  chronis:
    build: .
    container_name: chronis
    privileged: true
    user: root
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: false
      - ./:/app
    restart: unless-stopped
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production 